### PR TITLE
Refactor be code

### PR DESCRIPTION
**Pull request by JackieDan**
Creating and getting posts:
-Added the static folder for pictures
-Updating then models to fit post structure
-Added logic to create new posts and get list of posts for a user

### CODE REVIEW

**Review by Hamna-Akh — APPROVED** [review]
Refactored backend code looks good, approving changes.

**Review by NathanFortier — COMMENTED** [review]
why is picture model being removed? was it replaced?

**Comment by Hamna-Akh** [comment]
> why is picture model being removed? was it replaced?

Yes, rather than a picture model and a post model, the post will include picture. Meaning a post cannot be made without adding a picture.

**Comment by JackieDan** [comment]
> why is picture model being removed? was it replaced?

It was merged with the Post model for simplicity.

**Comment by Hamna-Akh** [comment]
Passes tests.

**Pull request merged**
