### PR TITLE
#14 Integrate Vue.js for frontend

### PR DESCRIPTION
**Pull request by JackieDan**
Implementing the Vue.js framework for the frontend and updating frontend README file

### CODE REVIEW

**Comment by Hamna-Akh** [comment]
Easy to follow, looks good.

**Comment by Hamna-Akh** [comment]
Easy to follow, looks good.

**Review by Hamna-Akh — APPROVED** [review]
Everything is in order, approving changes.

**Comment by NathanFortier** [comment]
Merging pull request.

**Pull request merged**
